name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby for Jekyll
      - name: Set up Ruby for Jekyll
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.x'

      # Step 3: Install Bundler and Jekyll dependencies
      - name: Install Bundler and Jekyll dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # Step 5: Debug _site directory (check if files exist)
      - name: Debug _site directory
        run: ls -al _site

      # Step 6: Install dependencies for Express app (if needed)
      - name: Install dependencies for Express app
        run: npm install

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          allow_empty_commit: true
